### ISSUE TITLE
Add Rubocop integration

### ISSUE THREAD

**Issue by xredo** [MarsBased/circleci#3]
## Description

We are currently using HoundCI tu execute Rubocop for our projects. However, we believe that we can unify this behaviour under our CI integration, to not have lots of separate services.

We want to be able to execute Rubocop in Circle CI, but using the same approach used by HoundCI (only analysing the code that changed between the PR target code and the code in the PR).

## Tech description

This is a post to execute Rubocop only on modified files. However, this is only half of the work that we want to do (it doesn't take into account the PRs): https://medium.com/devnetwork/running-rubocop-only-on-modified-files-a21aed86e06d

If it helps, you can also check the code being run by HoundCI: https://github.com/houndci/hound

We don't need to comment on PRs. We only want CircleCI to fail if there are rubocop problems.

**Comment by oriolbcn** [comment]
This is not as trivial as it sounds, we need to discuss this further before proceeding.

CircleCI runs both builds on branches (as soon as they are pushed to the repo) and on PRs.

# Non-PR runs

In this case there is no PR, just a branch that has been updated in the repository. As we already know, branches are just _tags_ added to a specific commit, so there is no way of knowing the "base" branch, since this information is not stored because it does not work this way.

# PR runs

When a CircleCI build is triggered from a PR, CircleCI makes a set of variables available with information on the PR. HOWEVER, it does not give information on the base branch. See [this discussion](https://discuss.circleci.com/t/access-real-branch-name-for-pull-request-fork-build/907/2) and [this other one](https://discuss.circleci.com/t/create-a-circle-target-branch-envar/10022/5).

As said in the discussions there are ways to hack this around using the Github API to get the actual base branch.

With the base branch we can do a `git-diff` and take only the files modified in the commits in between.

# Possible approaches

There is an option in CircleCI to only run builds on Pull Requests. We could activate that and then we could forget about non-PR runs.

If we want to have non-PR builds, we could do 2 things:
* Don't run rubocop in these builds.
* Compare always with master. The results would be misleading or meaningless when a PR is created from a branch that is not master, but in the end all commits should go in a PR to master at some point, so at the end of the day all commits would still be checked.
* Traverse the commits tree until we find a commit that is shared with another branch. We can then assume that this is the base branch. This would quite complex to implement, but feasible.

# My opinion

Depends on the answer to: Are we going to add CircleCI to an existing project any time soon?

If no: I would just run rubocop on all files always.
If yes: I would not run rubocop in non-PR builds and implement the Github API based approach for PR builds.

@xredo thoughts?

**Comment by xredo** [comment]
The idea was to have one size that fits all. And yes, we have some projects that are using CircleCI but are not 100% covered by Rubocop. However, we need to have a balance between work / gain.

How much do you think is going to take us develop the Github API based approach?

**Comment by oriolbcn** [comment]
It should not take more than half a day. We also need to decide what to do with non-PR builds.

**Comment by xredo** [comment]
I would not run rubocop in non-PR builds. This way we get the best of 2 worlds.

However, I would leave a comment in the circleci config and in the README indicating how to remove this condition and run full rubocop always.

**Comment by oriolbcn** [comment]
The drama continues, it cannot be done as I described. CircleCI does not initiate a new build when a PR is open (like other CIs do, example: Shippable and Travis).

So this it what happens:
1. Developer pushes a new branch to the repo.
2a. CircleCI triggers build.
2b. The developer prepares the PR.
3. The developer creates the PR.

For when the developer create the actual PR the build has already finished and so it didn't got the PR info (there was no PR while running the build!). So it gets treated as a non-PR build, and since the actual PR does not trigger any build, rubocop does not run.

The only way to accomplish this is by enabling the "Only build on PRs" option in the CircleCI project config. With this option, the build is not initiated until the PR is actually created and therefore the PR info is already available. Builds are also run in all commits of the main branch (master).

So we either:
* Assume that projects will have this option enabled and write the process relying on that.
* Implement one of the mechanisms I described to run rubocop in non-PR builds.
* Change CI provider.

More people frustrated with this: [this guy](https://discuss.circleci.com/t/pull-requests-not-triggering-build/1213), [this other guy](https://discuss.circleci.com/t/trigger-build-on-pr-and-commit-to-a-branch/24023) and [this dude](https://discuss.circleci.com/t/trigger-new-build-on-pr/4219)

**Comment by xredo** [comment]
Reached this point, I recommend always running rubocop for all the codebase. If there is a project that don't have a good coverage, we will use Hound instead and we will remove rubocop from the CircleCI config.

I am not planning to change the CI provider until Github Actions goes out of beta. I really want to see how it works and what pricing are they offering.
